export * from './budgets.service';
import { BudgetsService } from './budgets.service';
export * from './cVs.service';
import { CVsService } from './cVs.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categoryWiseReports.service';
import { CategoryWiseReportsService } from './categoryWiseReports.service';
export * from './incomeVsExpenseReports.service';
import { IncomeVsExpenseReportsService } from './incomeVsExpenseReports.service';
export * from './monthlyReports.service';
import { MonthlyReportsService } from './monthlyReports.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './savingsGoals.service';
import { SavingsGoalsService } from './savingsGoals.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export const APIS = [BudgetsService, CVsService, CategoriesService, CategoryWiseReportsService, IncomeVsExpenseReportsService, MonthlyReportsService, NotificationsService, SavingsGoalsService, TransactionsService];
