/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelCVResponse } from './entityModelCVResponse';


export interface CollectionModelEntityModelCVResponseEmbedded { 
    cVResponseList?: Array<EntityModelCVResponse>;
}

