/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CVRequest } from './cVRequest';


export interface CreateCVRequest { 
    cvRequest?: CVRequest;
    profileImage?: Blob;
}

