/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Experience } from './experience';
import { Education } from './education';
import { SocialLink } from './socialLink';


export interface CV { 
    id?: number;
    username?: string;
    fullName?: string;
    email?: string;
    phoneNumber?: string;
    address?: string;
    summary?: string;
    profileImage?: string;
    experiences?: Array<Experience>;
    educations?: Array<Education>;
    socialLinks?: Array<SocialLink>;
    skills?: Array<string>;
    languages?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
}

