/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EducationResponse { 
    degree?: string;
    institution?: string;
    startDate?: string;
    endDate?: string;
    cd_id?: number;
}

