/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelIncomeExpenseReport { 
    id?: number;
    year?: number;
    totalIncome?: number;
    totalExpense?: number;
    createdAt?: string;
    updatedAt?: string;
    _links?: { [key: string]: Link; };
}

