/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CV } from './cV';


export interface Experience { 
    id?: number;
    position?: string;
    company?: string;
    startDate?: string;
    endDate?: string;
    description?: string;
    cv?: CV;
}

