/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonthlyReport { 
    id?: number;
    year?: number;
    month?: number;
    totalIncome?: number;
    totalExpense?: number;
    categoryWiseExpenses?: string;
    createdAt?: string;
    updatedAt?: string;
}

