/**
 * Personal Finance Management API
 *
 * Contact: dragisa@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CV } from './cV';


export interface SocialLink { 
    id?: number;
    platform?: string;
    url?: string;
    iconClass?: string;
    cv?: CV;
}

